In [1]:
import numpy as np

In [6]:
A = np.array([[1,2,3],[4,5,6],[7,8,8]])

In [7]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 8]])

## Linear Algebra

In [8]:
from scipy import linalg

In [9]:
# Compute the determinant of a matrix
linalg.det(A)

3.0

Compute pivoted LU decomposition of a matrix. The decomposition is:

    A = P L U

where P is a permutation matrix, L lower triangular with unit diagonal elements, and U upper triangular.

In [10]:
P, L, U = linalg.lu(A)

In [13]:
P

array([[0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.]])

In [14]:
# the eigenvalues and eigenvectors of this matrix
EW, EV = linalg.eig(A)

In [15]:
EW

array([15.55528261+0.j, -1.41940876+0.j, -0.13587385+0.j])

In [16]:
EV

array([[-0.24043423, -0.67468642,  0.51853459],
       [-0.54694322, -0.23391616, -0.78895962],
       [-0.80190056,  0.70005819,  0.32964312]])

In [18]:
v = np.array([[2],[3],[5]])
v

array([[2],
       [3],
       [5]])

In [19]:
# Solving systems of linear equations A * s = v
s = linalg.solve(A,v)

In [20]:
s

array([[-2.33333333],
       [ 3.66666667],
       [-1.        ]])